default:
  tags:
    - macthreadaqa

stages:
  - tests
  - allure

API Tests:
  stage: tests
  allow_failure: true
  script:
    - chmod +x gradlew
    - ./gradlew -x test apiTests
  artifacts:
    when: always
    paths:
      - build/allure-results

Allure report:
  stage: allure
  script:
    - - chmod +x gradlew
    - ./gradlew allureReport
    - echo "Allure report live here - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/build/reports/allure-report/allureReport/index.html"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/*
